### ISSUE TITLE
may you clarify what is it 100x different models

### ISSUE THREAD

**Issue by Sandy4321** [aws-samples/amazon-sagemaker-pipeline-deploy-manage-100x-models-python-cdk#2]
This approach allows for the creation and training of 100x different models, with each model associated with a distinct DummyDimension.

may you clarify what is it 100x different models
do you have video for this project how to use?

**Comment by dineshmane** [comment]
I don't have the video.

To further explain what 100x means here:
You can train unique model for each dimension e.g. city, country, customer profile and others....

In your use case, if you have 20 cities then you can train and deploy total 20 models, each model associated to unique city using the same SageMaker pipeline. 

If you have further doubts feel free to reopen the issue. thanks.
