### ISSUE TITLE
may help to understand where in your code you use files for training 

### ISSUE THREAD

**Issue by Sandy4321** [aws-samples/amazon-sagemaker-pipeline-deploy-manage-100x-models-python-cdk#4]
may help to understand where in your code you use files for training 
https://github.com/aws-samples/amazon-sagemaker-pipeline-deploy-manage-100x-models-python-cdk/tree/main/sagemaker_pipeline_deploy_manage_n_models_cdk/dataset/training-dataset

**Comment by dineshmane** [comment]
CDK will create training-bucket and when files are dumped in that S3 bucket, it will trigger SageMaker pipeline via Lambda. 

https://github.com/aws-samples/amazon-sagemaker-pipeline-deploy-manage-100x-models-python-cdk/blob/76a3a9043d5d327b3f9322548c2ab021eef3fe85/sagemaker_pipeline_deploy_manage_n_models_cdk/stacks/start_sagemaker_pipeline_stack.py#L36-L46

**Comment by Sandy4321** [comment]
any you share additional material how to retrain model in production when new data file added to s3 bucket pls
